### ISSUE TITLE
Plugins cannot be loaded if they do not inherit from a base type

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#100]
The current implementation assumes that all plugins inherit from a common base type (which you provide to the config in order to allow them to be discovered)

This does not cope with the situation where plugins have been build implementing IPlugin directly rather than via a base type - the discovery process is unable to find these.

**Comment by TomMalow** [comment]
That is a good point. The current implementation is based on our own way of handling plugins which originate from the Daxif tool. But i can see that can be limiting. 

Don't know when we will look at it but it is a good things to fix to make XrmMockup more general available

**Comment by magesoe** [comment]
Added in 1.4.0
