### ISSUE TITLE
Plugins steps with a blank primary entity name are not retrieved by the metadata generator

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#102]
Plugin steps where the primary entity name is blank (as with associate/disassociate plugins) are ignored by the metadata generator, due to the inner join on sdkmessagefilter.

In some cases the primary entity name is stored as the value "none"  - these steps are retrieved as expected but then "none" is used as the primary entity name.

**Comment by TomMalow** [comment]
Just be sure. Given this description, then XrmMockup will not trigger either of these plugins?

**Comment by magesoe** [comment]
Added in 1.3.3
