### ISSUE TITLE
Support plugins running as a configured user rather than the calling user

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#105]
![image](https://user-images.githubusercontent.com/35061073/88482844-c1e1dd80-cf5b-11ea-8dc8-e046abf0877b.png)

Plugins can be set to run either as "calling user" (the default) or a as a specified user. The specified user setting is usually used to run the plugin with elevated permissions to allow it perform work that the calling user does not have permission to.

It would be really useful for XRMMockup to support this feature.

**Comment by magesoe** [comment]
Added in 1.4.6
