### ISSUE TITLE
Security Checks occuring in wrong point in the create process ?

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#106]
Bear with me - this is long

2 Entities - Parent & Child

Plugin on Parent entity (post operation, running as system admin) to assign the entity to an owning team (with no members and no privileges except "read" on the entity)

Plugin on the Child entity (pre operation, running as calling user) to create the parent entity, and set the lookup value on the child to it

So sequence is :-
User creates Child entity
Child entity plugin creates Parent entity
Parent entity plugin sets Parent Owner to owning team
Child entity plugin sets lookup value on entity to new parent entity
CRM saves child entity

In Dynamics this all works fine.
In XRMMockup, the final save fails with 
  **Message=Trying to create entity 'new_annex', but the calling user with id '8c849bf5-c84d-4886-b948-0afce5693f86' does not have AppendTo access for referenced entity 'new_section' on attribute 'new_section'**

which kinda makes sense - the creating user no longer does have AppendTo access on the parent entity as he is no longer the owner of it (because its been assigned to a record owning team)

The implication is that Dynamics is doing the AppendTo access check *before" the plugins run...?

**Comment by MattTrinder1** [comment]
As an update, I’m in discussion with MS support about why this works in Dynamics.

**Comment by magesoe** [comment]
Perhaps it is because of when XrmMockup does validation. Right now security is done in each request, but Dynamics does security in the validation step. I think the discrepancy lies there. Also it comes down to what goes on in a transaction, which XrmMockup doesn't truly support atm.

**Comment by MattTrinder1** [comment]
(Finally) had a reply back from MS support on this one - they've confirmed what you stated, the security checks are done in the pre-validation step (so, in this case, before the plugins have run to change the owners around).
Not sure what the resolution is for this for XRMMockup - extract the security checks to a system\special case plugin which runs first in pre-validation ?

**Comment by magesoe** [comment]
That is exactly what we have to do. A generic handler that takes a request and handles security

**Comment by MattTrinder1** [comment]
Would you like me to take a look at that ? - this issue is directly affecting me being able to use XRMMockup on one of our major projects so I'm keen to get it resolved.

**Comment by magesoe** [comment]
I would always love if you fix issues :)

**Comment by MattTrinder1** [comment]
kk - can't make any promises how soon though :-)

**Comment by magesoe** [comment]
Added in 1.5.0
