### ISSUE TITLE
Plugins with the same FQN in different assemblies cause steps to be registered incorrectly

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#123]
As an example, I have 2 plugins called CAMS.Xrm.Plugins.MilestoneCreate, but in different assemblies. Dynamics copes with this fine.

However, when the plugins are registered in PluginManager.RegisterPlugin the line

```
 var metaSteps = plugins.Where(x => x.AssemblyName == basePluginType.FullName).ToList();
```

finds all the registration steps for both plugins as it is not distinguishing on the assembly name.

The MetadataGenerator needs to pickup and record the assembly name for each step from Dynamics and the above line needs to check this in addition to the plugin name.

**Comment by magesoe** [comment]
Added in 1.6.0
