### ISSUE TITLE
Error messages thrown from XrmMockup should match those thrown by Dynamics

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#150]
or at least contain a sensible subset of the error message text.

A large proportion of our tests are checking for specific security exceptions - and these fail when run using XrmMockup as the exception messages are different

for instance a lot of our test code look like this

```

try
            {
                Connections.AppendixManager.Execute(assoc);
                Assert.Fail("non stakeholder should not be able to add a p9 line");
            }
            catch (Exception ex)
            {
                Assert.IsTrue(ex.Message.Contains("SecLib::AccessCheckEx2 failed"));
            }
            finally
            {

            }

```

**Comment by magesoe** [comment]
Only messages that specifically relate to this error have been fixed, more work still needs to be done on this topic.

Added in 1.6.2
