### ISSUE TITLE
Fields added to entities by plugins should not be visible in the original entity saved by the user once the save has completed.

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#164]
Happens because XrmMockup passes the same entity by reference all the way through the save process - in Dynamics the entity created and saved by the user is entirely disconnected from the save (passed by value) and so remains unaffected by any changes made by plugins.

Easiset fix is probably for the actions on MockupService to call CloneEntity on the passed in entity before calling SendRequest.

**Comment by magesoe** [comment]
Added in 1.7.6
