### ISSUE TITLE
"Matches" needs to implemnt BeginsWith/EndsWith and the Not versions

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
- CRM/D365/CDS version: [e.g. 9.1.x]
- Tool version: [e.g. 3.2.1]
- Other applicable environments

**Additional context**
Add any other context about the problem here. Error messages og solution files.

**Comment by magesoe** [comment]
Added in 1.7.5
