### ISSUE TITLE
Workflows which update the parent record when running on a child record fail

### ISSUE THREAD

**Issue by MattTrinder1** [delegateas/XrmMockup#172]
The parent entity is referred to in the workflow xml like

`<Assign x:TypeArguments="s:Guid" To="[CreatedEntities(&quot;related_cams_agreementplanid#cams_agreementplan#Temp&quot;).Id]" Value="[InputEntities(&quot;related_cams_agreementplanid#cams_agreementplan&quot;).Id]" />`
																		
XrmMockup needs to cope with the "related_"

**Comment by magesoe** [comment]
Added in 1.7.9
