### ISSUE TITLE
After generating metadata, inform the user it is completed

### ISSUE THREAD

**Issue by rappen** [delegateas/XrmMockup#176]
Running MetadataGenerator365.exe according to step 4 in https://github.com/delegateas/XrmMockup/wiki/Setup
It seems to hang on **Writing files**

![image](https://user-images.githubusercontent.com/2572253/105506942-e5979d80-5cca-11eb-919e-602573b461f8.png)

But I assume this really means it is finished?
Better feedback would be nice, so I don't have to be afraid I killed it prematurely.

**Comment by magesoe** [comment]
It should send some kind of feedback, otherwise this is a mistake. Will investigate 
![image](https://user-images.githubusercontent.com/8904582/105715323-c17fca80-5f1d-11eb-9b52-7fe4a5444837.png)

**Comment by misoeli** [comment]
The success message from magesoe's screenshot is in DAXIF, not XRMMockup. Should be a relatively easy fix.
