### ISSUE TITLE
Plugin Images are missing

### ISSUE THREAD

**Issue by Kato88** [delegateas/XrmMockup#201]
**Describe the bug**
When generating metadata for a plugin step with an entity image it will not be executed with that image.

**To Reproduce**
1. Setup MetadataGenerator365.exe to read from solutions
2. Do not fetch from Assemblies, don't use DAXIF
3. Have a plugin with entity images registered
4. Generate Metadata
5. Create a basic test for a plugin (**_Without DAXIF_**) that uses an entity image

**Expected behavior**
The plugin will be loaded and executed with the images

**Screenshots**
MetadataGenerator365.DataHelper.GetPlugins Method that displays that the sdkmessageprocessingstep has an empty guid.
![image](https://user-images.githubusercontent.com/4804015/149351721-11e34a07-cd0b-49e4-9fc6-da63c0198615.png)

**Environment**
- D365
- Without DAXIF

**Additional context**
When loading sdkmessageprocessingstep and images from an environment, the images are not matched to the sdkmessageprocessingstep. This is because the Id of the sdkmessageprocessingstep is not retrieved.
#202

**Comment by misoeli** [comment]
Thank you for your report, and PR.

I'm not that well versed in the details of setting up non-DAXIF plugins for testing, but I do not see any issue when testing the PR out. However, I didn't really manage to identify a change in the test either, when applying the change. So just to clarify, did the linked PR (#202 ) solve the issue for you, or is that a qualified guess as to what the problem could be?

**Comment by Kato88** [comment]
Yes it solved the issue

**Comment by Kato88** [comment]
Issue was resolved after pull request got merged. Thanks <3

**Comment by misoeli** [comment]
Included in 1.10.0.
