### ISSUE TITLE
Add RetrieveCurrentOrganizationRequest

### ISSUE THREAD

**Issue by Kato88** [delegateas/XrmMockup#217]
**Is your feature request related to a problem? Please describe.**
You cannot retrieve things like the current orgs url without the RetrieveCurrentOrganizationRequest.

**Describe the solution you'd like**
Add an additional Request and the possibility to define the Organization Detail Property using the XrmMockupSetting object.

**Describe alternatives you've considered**
I think I tried everything to get it working without adding the request. Even drunk and using reflection.

Pull Request adding the feature is incoming <3

**Comment by misoeli** [comment]
Added in 1.12
