### ISSUE TITLE
OOB Calculated string Field with DateTime value (incident.caseage)

### ISSUE THREAD

**Issue by Kato88** [delegateas/XrmMockup#219]
**Describe the bug**
Calculated field that tries to write a DateTime to a string field fails.
This happend for a OOB field "caseage" on entity "incident".

**To Reproduce**
Generate metadata with caseage attribute of incident and update an incident.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4804015/207302528-a9874cc0-39c0-4133-b4aa-a5417d3f13df.png)

**Environment**
- D365 Online - latest Sandbox
- Tool version: 1.11.2
- Also including the PR for #217 locally

I will add a PR that will add the check for DateTime.

**Comment by misoeli** [comment]
Should already be resolved as part of 1.10.1 (issue #209). Let me know if you see any issues with that resolution.
