### ISSUE TITLE
Add support for IsValidStateTransitionRequest and RetrieveExchangeRateRequest 

### ISSUE THREAD

**Issue by magesoe** [delegateas/XrmMockup#28]
The documentation for the two requests can be seen below.

https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.isvalidstatetransitionrequest.aspx
https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.retrieveexchangeraterequest.aspx

**Comment by Ladekarl** [comment]
#44
