### ISSUE TITLE
Status reason not set to default value on create

### ISSUE THREAD

**Issue by lisby** [delegateas/XrmMockup#35]
Status reason is not set to default value on create. This can be an issue if status reason transitions are applied, as the first status change is always valid (as there's no from state)

**Comment by magesoe** [comment]
Jeg er ikke enig at det ikke er tilføjet. Følgende kode i CreateRequestHandler.cs skulle gerne tilføje den
```csharp
if (!clonedEntity.Attributes.ContainsKey("statuscode") &&
    Utility.IsSettableAttribute("statuscode", entityMetadata)) {
    var statusMeta = attributes.FirstOrDefault(a => a.LogicalName == "statuscode") as StatusAttributeMetadata;
    clonedEntity["statuscode"] = statusMeta.DefaultFormValue.HasValue ? new OptionSetValue(statusMeta.DefaultFormValue.Value) : new OptionSetValue(1);
}
```

Kan du lave en test med standard entiteter, hvor det ikke virker?

**Comment by lisby** [comment]
Agreed - that should do it. The following test fails though:
```
        [TestMethod]
        public void TestIncidentStatuscode()
        {
            var incidentId = orgAdminService.Create(new Incident { });
            var incident = HBD.GetEntity<Incident>(orgAdminService, incidentId);

            Assert.AreEqual(Incident_StatusCode.InProgress, incident.StatusCode);
        }
```

orgAdminService is interchangeable with a "default" user orgService, the issue still occur.

**Comment by magesoe** [comment]
The test also fails for me. DefaultFormValue seems to be -1 despite changing the default value. I will investigate how it chooses the value if the default value is -1
