### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CrmDev23** [delegateas/XrmMockup#37]
Hi guys
This is more a question rather than an issue: I tried to setup my project for unit testing according your guide. Additionally I'm also using the delegate custom crm context. When I try to run my first unit test, I get this message:
![debugging](https://user-images.githubusercontent.com/13016624/34949862-acf8aaec-fa11-11e7-811d-763afe715291.png)
I guess it's supposed to work with the delegate custom crm context. Do I missing something?
Thanks!

**Comment by TomMalow** [comment]
Hi CrmDev23

Nice to hear that you are using XrmContext as well!

My guess is that you haven't enabled proxy type when creating the XrmMockup instance defined with the `XrmMockupSetting` class.

Our [wiki](https://github.com/delegateas/XrmMockup/wiki/Setup) shows how we suggest that the XrmMockup instance is to be created in the base test class.

**Comment by CrmDev23** [comment]
Thanks for your answer! I took the code shown in your documentation, where the `EnableProxyTypes` is set to true. So I think, this is not the problem.

**Comment by CrmDev23** [comment]
I checked my configuration again: In the BasePluginTypes I've added the specific plugin's instead of the base class. After changing this config to the base class everything works fine.
I'm planning to use your framework for my project, although it's in beta stage. Should I expect any bigger changes (refactorings) for the coming months?

**Comment by magesoe** [comment]
Awesome that it works now. We don't plan on making any breaking changes and if we do the version of the nuget will indicate it by having a new major version.
