### ISSUE TITLE
Throw better error for calculated fields without formula definition

### ISSUE THREAD

**Issue by jonatangranner** [delegateas/XrmMockup#48]
Having calculated fields without any formula definition will cause XrmMockup to throw an exception with message "Unknown type when parsing calculated attr" for any retrieve requests to the entity with the calculated field. (RetrieveRequestHandler.cs, 84)
It would be nice to have a check for whether a formula definition is available and if not throw an exception with message such as "No formula has been set for the calculated field: {fieldname}".

**Comment by mkholt** [comment]
This is actually worse than it seems.
If no formula is set on ANY calculated field on an entity, ANY retrieve call will fail on that entity.
Even if that field is not a part of the retrieve, or in any way relevant.

This in addition to CRM being quite able to handle empty formulas means we should probably handle this differently.

We have a suggestion from a client to add an option to XrmMockup: bool IgnoreEmptyFormulaDefinitions

If this is set to true, XrmMockup should return an empty value for the field when queried, and optionally write a warning message to inform the user about the issue.

**Comment by magesoe** [comment]
Added in 1.3.3
