### ISSUE TITLE
Handle requests based on its name instead of just its type.

### ISSUE THREAD

**Issue by mktange** [delegateas/XrmMockup#5]
Currently requests are handled based on the type of the request object. However, requests can also be sent as just the base class (`OrganizationRequest`), but where it has been given a name and necessary parameters which corresponds to requests of the type with that request name.

Handle un-typed requests by identifying which type it is based on the name of the request.

**Comment by magesoe** [comment]
A possible solution would be to change
`request is RetrieveMultipleRequest`
to
`request.RequestName == new RetrieveMultipleRequest().RequestName`

**Comment by magesoe** [comment]
Solved in commit 9b8aa22aad9841fa84a4d00d79a220ff680e91d6
