### ISSUE TITLE
Security Role generation

### ISSUE THREAD

**Issue by skovlund** [delegateas/XrmMockup#50]
**Description**
Running a metadata generator executable _(only tested with MetaDataGenerator365.exe)_ does not generate Security Roles correctly. Not all privileges are included in all roles. The issue lies with the retrieval of privileges using a query with both paging and linked entities. This does not seem to be supported (although I have found no documentation verifying this). Changing the paging size influence which records are retrieved.

**Fix**
Retrieve entities without linking, then join locally afterwards.

**Comment by TomMalow** [comment]
Fixed in https://github.com/delegateas/XrmMockup/commit/6e6b6517e1ff8bc6058645a6c96bf2aedb5e8e7c

**Comment by henrikhannemose** [comment]
Thanks for the fix :)

We have since learned more about the cause of this. The underlying issue was that paging cookies are broken in CRM. See [Dynamics CRM Paging Cookies – some gotchas!](https://truenorthit.co.uk/2014/07/19/dynamics-crm-paging-cookies-some-gotchas/) for an explanation.
