### ISSUE TITLE
Unknown privilege depth mask: 0

### ISSUE THREAD

**Issue by aronmek** [delegateas/XrmMockup#52]
When running the metadata generator I'm getting the above mentioned error
**Unknown privilege depth mask: 0**.
Looking into the[ source code](https://github.com/delegateas/XrmMockup/blob/master/src/MetadataShared/DataHelper.cs#L356) it seems that the mapping is different than the [dynamics options](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.privilegedepth.aspx#Anchor_1).

Can someone clarify?

Thanks.

**Comment by aronmek** [comment]
Doing some more research it seems that the privilegedepthmask field on the roleprivilege entity does not map directly to the PrivilegeDepth enum.
Querying my system for the 0 privilegedepthmask records it seems that all of those records are privileges on the [ExpanderEvents entity](https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/entities/expanderevent) which is an internal use entity, so i guess that the privilege depth of 0 is also internal.

It seems unreasonable to crash for unknown depth at this point. If so, How should we deal with those role privileges?

**Comment by TomMalow** [comment]
That is quite an interesting issue you have encountered. We haven't had this problem before. I even tried to retrieve the role privilege for the same entity through metadata generator and by using the same query expression as in the [code](https://github.com/delegateas/XrmMockup/blob/92003f7425cc87822d0bc7fcfe9b2cd237bf2277/src/MetadataShared/DataHelper.cs#L290). 

My guess is that your system has an incorrectly created role privilege where the value of the `privilegedepthmask` is set to 0, which is invalid. The page [you have referenced](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.privilegedepth.aspx#Anchor_1) specifies that valid values of `privilegedepthmask` are 1, 2, 4, and 8. (Note that even though they say it is only for LINQ. The values also holds for QueryExpression).

Have you perhaps at some point created some roles through code or a third-party system? This might be the cause of the incorrectly defined role privileges. The solution is perhaps to either fix this through code or delete the affected security role and recreate it.

**Comment by aronmek** [comment]
Below is an export from a linqpad resultset for the affected records. These are system records which was introduced in version 9.

FriendlyName | Description | PrivilegeDepthMaskΞΞ | RoleName | PrivilegeName | IntroducedVersion
-- | -- | -- | -- | -- | --
System Solution | Internal CRM System Solution | 0 | Vice President of Marketing | prvReadExpanderEvent | 9.0.0.0
System Solution | Internal CRM System Solution | 0 | Vice President of Marketing | prvWriteExpanderEvent | 9.0.0.0
System Solution | Internal CRM System Solution | 0 | Marketing Professional | prvWriteExpanderEvent | 9.0.0.0
System Solution | Internal CRM System Solution | 0 | Marketing Professional | prvAppendToExpanderEvent | 9.0.0.0
System Solution | Internal CRM System Solution | 0 | Marketing Professional | prvReadExpanderEvent | 9.0.0.0
System Solution | Internal CRM System Solution | 0 | Vice President of Marketing | prvAppendToExpanderEvent | 9.0.0.0

**Comment by TomMalow** [comment]
Do you have any other 9.0 instances with the same problem?

I definitely think that your problem is in your dynamics 365 instance. After a quick google search I found that there have previously been similar issues regarding incorrect privilege depth mask. An example is found in this [post](https://community.dynamics.com/crm/f/117/t/207450). Are you able to edit the affected Security Roles?

My suggestion is to either try to modify the affected security roles and give Organization level privilege to the related entity, Expander Events (However i don't think this is possible). Otherwise open a ticket with Microsoft Support and I think they can fix it.

**Comment by aronmek** [comment]
I had it on both, my prod instance and sandbox environment.
I tested it with a fresh environment and you're right, it didn't have those roles with the mask of 0.
Fortunately I was able to change the infected records in my environment.

Thanks for your help. 
_I'm closing this task._
