### ISSUE TITLE
MetadataGenerator16 throws an error

### ISSUE THREAD

**Issue by DevproCH** [delegateas/XrmMockup#56]
When I run the MetadataGenerator, it throws an error while getting default state and status. I have run the tool on another CRM Organization and it works perfectly. Does anyone have an idea how to fix this issue? Is there a way to increase the timeout time?

## Console output

Generation of metadata files started
Getting entity metadata
Retrieved entity metadata for: businessunit, systemuser, transactioncurrency, role, systemuserroles, teamroles, activitypointer, account, new_systemuser_systemuser_identitytakeover
Getting currencies
Getting plugins
Getting organization
Getting root businessunit
Getting All Optionsets
Getting Default state and status

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: SQL timeout expired.

Server stack trace:
   bei System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   bei System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   bei System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   bei System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   bei System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   bei System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   bei Microsoft.Xrm.Sdk.IOrganizationService.RetrieveMultiple(QueryBase query)
   bei Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.RetrieveMultipleCore(QueryBase query)
   bei Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy.RetrieveMultiple(QueryBase query)
   bei DG.Tools.XrmMockup.Metadata.DataHelper.GetDefaultStateAndStatus() in C:\git\XrmMockup\src\MetadataShared\DataHelper.cs:Zeile 429.
   bei DG.Tools.XrmMockup.Metadata.DataHelper.GetMetadata(String path) in C:\git\XrmMockup\src\MetadataShared\DataHelper.cs:Zeile 75.
   bei DG.Tools.XrmMockup.Metadata.Program.GenerateMetadata() in C:\git\XrmMockup\src\MetadataShared\Program.cs:Zeile 52.
   bei DG.Tools.XrmMockup.Metadata.Program.Main(String[] args) in C:\git\XrmMockup\src\MetadataShared\Program.cs:Zeile 37.

**Comment by TomMalow** [comment]
Hi @DevproCH and sorry for the (extremely) long respond time

Do you get this error consistently?
It does not look like you are fetching a whole lot of data and would seem odd that such a few number of entities can cause a SQL timeout. 

We have recently made some changes to how the Metadata Generator fetches some of the data. See if the issue have been resolved in any of the latest version. If you still are experiencing issues then please let us know.

**Comment by magesoe** [comment]
Closing due to 1 month inactivity. Reopen if it's still relevant
