### ISSUE TITLE
Setup Travis-CI to build and test using the FAKE build script

### ISSUE THREAD

**Issue by mktange** [delegateas/XrmMockup#6]

**Comment by mktange** [comment]
It seems that Mono doesn't support workflow/wpf yet:

![image](https://user-images.githubusercontent.com/3582986/28567568-fbf5c3d6-7132-11e7-8697-2ee2061d6878.png)

![image](https://user-images.githubusercontent.com/3582986/28567597-1a84cbbc-7133-11e7-9931-5936f32bc6d1.png)

We might need to consider using another form of CI that does not use Mono.

**Comment by magesoe** [comment]
This has been done using Appveyor instead
