### ISSUE TITLE
Need to load assembly containing early bound types before instantiating XrmMockup

### ISSUE THREAD

**Issue by henrikhannemose** [delegateas/XrmMockup#66]
XrmMockup throws the following error for me: 

> Unable to cast object of type 'Microsoft.Xrm.Sdk.Entity' to type 'DG.XrmFramework.BusinessDomain.ServiceContext.BusinessUnit

On 15/3-18 I can see that I/we looked further into this. If the assembly containing the early bound classes is not loaded before XrmMockup is initialized, I get the above error. If instead I load one of the early bound classes before initializing XrmMockup (thereby loading the assembly), everything works as expected. Thus I have had the following hack in place since March:

    public static void InitializeMockup(TestContext context) {
       var tmpAccount = new Account(); //TODO: Temp fix to ensure BusinessDomain-assembly is loaded before running mockup. Awaits a new mockup-release
        var settings = new XrmMockupSettings { [...] };
        crm = XrmMockup365.GetInstance(settings);
        [...]
        };

@jonatangranner and @Tolini now experienced the same issue, so we started talking about this again. I can not see that any permanent fix has made it into XrmMockup. Does anybody recall the status of this?

**Comment by magesoe** [comment]
Fixed in version 0.10.2
