### ISSUE TITLE
Cannot Generate Metadata for XrmMockup

### ISSUE THREAD

**Issue by Ladekarl** [delegateas/XrmMockup#67]
Generating metadata for XrmMockup is failing.

When running GenerateXrmMockupMetadata the following error is outputted:
> Executing for 11
...
> (2018-08-14 11:29:19Z) [Error]: Unhandled Exception: System.InvalidOperationException: Metadata contains a reference that cannot be resolved: 'https://delegatelab4.crm4.dynamics.com/XRMServices/2011/Organization.svc?wsdl=wsdl0'. ---> System.InvalidOperationException: There is an error in XML document (1, 1384). ---> System.Xml.XmlException: The maximum nametable character count quota (16384) has been exceeded while reading XML data.

By removing metadata generation of CRM 2011 (version 5) I get a new error for CRM 2013:
> Executing for 13
...
> (2018-08-14 12:28:34Z) [Error]: Unhandled Exception: System.NotImplementedException: Unknown privilege depth mask: 0
> (2018-08-14 12:28:34Z) [Error]:    at DG.Tools.XrmMockup.Metadata.DataHelper.PrivilegeDepthToEnum(Int32 privilegeDepth) in C:\git\XrmMockup\src\MetadataShared\DataHelper.cs:line 394

This can be solved by changing DataHelper.cs line 344 from:
`if (entityName == "none") continue;` 
to
`if (entityName == "none" || (int)e.rpr.roleprivilege["privilegedepthmask"] == 0) continue;`
However, I am not sure this is the correct solution.

Metadata is now successfully generated for CRM 2013, but fails again for 2015 with the following error:

> Executing for 15
...
> (2018-08-14 12:34:55Z) [Error]: Unhandled Exception: System.ServiceModel.Security.MessageSecurityException: An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail. ---> System.ServiceModel.FaultException: Authentication Failure

After removing both CRM 2011 and CRM 2015 from metadata generation, it succeeded.
This means we can no longer connect SDK versions 5 and 7 to a Dynamics 365 v. 9.0 instance. Microsoft does not promise any forward compatibility so this was to be expected.

A solution is to spin up a VM for each CRM version we support. This is also preferable for testing purposes.

This [post](https://blogs.msdn.microsoft.com/crm/2017/02/01/dynamics-365-sdk-backwards-compatibility/) indicates that SDK version 8.x is backwards compatible with v6.x, v7.x, & v8.x. If this is true we might not need to use seperate SDK's for these versions, but it would still be a good idea to have the VMs for testing purposes.

**Comment by magesoe** [comment]
Given the roadmap of CRM's online future, I will not put anymore focus on this topic. At some point I would like to see XrmMockup having a single version that matches the current version of CRM, thus deprecating all previous versions of CRM. Therefore, I am closing this issue.
