### ISSUE TITLE
Implement SendEmailRequest

### ISSUE THREAD

**Issue by dbdness** [delegateas/XrmMockup#75]
The engine throws a `NullReferenceException` when encountering the execution of a `SendEmailRequest` object. Documentation for the request is [here](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg308290(v%3dcrm.8)).

**Comment by krihvi** [comment]
While implementing this could the request "SendEmailFromTemplateRequest" - Documentation [here](https://docs.microsoft.com/en-us/previous-versions/dynamicscrm-2016/developers-guide/gg308289(v=crm.8))
