### ISSUE TITLE
Metadatagenerator bug at Pre and PostImage

### ISSUE THREAD

**Issue by catalin-ilie** [delegateas/XrmMockup#79]
**Describe the bug**
In the query for retrieving the Sdk Step Images, the uniquename attribute is hardcoded to new [] { "PwCOrlenFlotaRelease001"}, whereas it should be the already created above object 'solutions', which contains the parsed solution names from the config file.

**To Reproduce**
1. Create a plugin with Pre and Post Images of the update step
2. try to generate Metadata
3. Images attribute of MetaPlugin is empty

**Environment**
- D365 v.9.0

**Comment by magesoe** [comment]
Added in 1.2.0
