### ISSUE TITLE
Custom Workflows with optional parameters trigger errors

### ISSUE THREAD

**Issue by catalin-ilie** [delegateas/XrmMockup#81]
**Describe the bug**
If the custom workflow has optional parameters that are not set at trigger, these are considered as activities and ConvertType is called, although no value is in the list. A second error occurs at CallCodeActivity invoker.Invoke(arguments), when an optional parameter has type DateTime and value null.

I was able to fix these by adding, resp. modifying following lines in WorkflowTree class:

line 1200: 
`if (!variables.ContainsKey(Input))
            {
                variables.Add(Input, null);
                variables.Add(Result, null);
                return;
            }`
line 1543:
`var arguments = this.inArguments.Where(arg => !outArguments.ContainsKey(arg.Value) && variablesInstance[arg.Value] != null).ToDictionary(arg => arg.Key,
                arg => (outArguments.ContainsKey(arg.Value) ? null : variablesInstance[arg.Value]));`

**To Reproduce**
1. Create Workflow with optional parameters, of type string, lookup on user, datetime
2. Create a test that triggers the custom workflow
3. Errors will be thrown

**Expected behavior**
Optional parameters which are not set should be ignored by XrmMockup in the flow

**Environment**
- D365 9.x

**Comment by magesoe** [comment]
Can you create a pull-request with the fix? Then you also get credited with the fix :)

**Comment by catalin-ilie** [comment]
unfortunatelly i get some git conflicts about my credentials and i am not able to push anything on xrmmockup repo

**Comment by magesoe** [comment]
That is because you're trying to push to the main branch. Read more about it here, it will guide you through making a pull request https://help.github.com/en/articles/creating-a-pull-request

**Comment by magesoe** [comment]
Added in 1.2.0
