### ISSUE TITLE
Athentication using ClientSecret

### ISSUE THREAD

**Issue by maerger** [delegateas/XrmMockup#95]
We are using an D365 online sandboxed instance for development at our customers site. As we are not allowed to have "non MFA" user accounts we get a Application and Client secret.
It would be nice to have ClientSecret authentication or MFA enabled user authentication (Oauth) for the metadata Generator. Otherwise we cannot use XrmMockup in our project...

**Comment by magesoe** [comment]
You can authenticate using OAuth and Client Secret. It seems I need to update the wiki for XrmMockup, but by setting the `method` parameter to `OAuth` or `ClientSecret` you switch the authentication method. 
The wiki Daxif is updated with the different authentication methods https://github.com/delegateas/Daxif/wiki/Using-different-auth-methods

And the parameters that you can use are the same as XrmContext and XrmDefinitelyTyped, so you can set 
| Argument      | Shorthand | Description  |
| ------------- |:---------:| ------------|
| mfaAppId          |             | Azure Application Id
| mfaReturnUrl      |             | Return URL of the Azure Application
| mfaClientSecret   |             | Azure Application Secret
| method            |             | Proxy, OAuth or ClientSecret

**Comment by maerger** [comment]
That would be very nice - I tried to update my "MetadataGenerator365.exe.config" that way (no luck at all):
![image](https://user-images.githubusercontent.com/6177363/77411302-8328f480-6dbc-11ea-9482-cba93ac55604.png)

**Comment by magesoe** [comment]
You set `ap` to be `ClientSecret`
Try setting it up like this, notice that the raw url is used instead of the old 2011 end-point
![image](https://user-images.githubusercontent.com/8904582/77412113-bcae2f80-6dbd-11ea-86d2-d1012e4112c5.png)

**Comment by maerger** [comment]
Added like you mentioned:
![image](https://user-images.githubusercontent.com/6177363/77418524-4ca4a700-6dc7-11ea-83a7-acef86273186.png)

When I start I get the following Error:
```
System.MissingMethodException: Methode nicht gefunden: "Void Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(System.Uri, System.String, System.Security.SecureString, Boolean, System.String)".
   bei DG.Tools.XrmMockup.Metadata.AuthHelper.Authenticate()
   bei DG.Tools.XrmMockup.Metadata.Program.GenerateMetadata() in C:\git\XrmMockup\src\MetadataShared\Program.cs:Zeile 54.
   bei DG.Tools.XrmMockup.Metadata.Program.Main(String[] args) in C:\git\XrmMockup\src\MetadataShared\Program.cs:Zeile 3
```

I have the following nuget packages:
```
  <package id="Microsoft.CrmSdk.CoreAssemblies" version="9.0.2.23" targetFramework="net462" />
  <package id="Microsoft.CrmSdk.Deployment" version="9.0.0.5" targetFramework="net462" />
  <package id="Microsoft.CrmSdk.Workflow" version="9.0.0.5" targetFramework="net462" />
  <package id="Microsoft.CrmSdk.XrmTooling.CoreAssembly" version="9.0.0.5" targetFramework="net462" />
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.19.8" targetFramework="net462" />
  <package id="Nexplore.Rulesets" version="1.0.34" targetFramework="net462" developmentDependency="true" />
  <package id="NUnit" version="3.12.0" targetFramework="net462" />
  <package id="NUnit3TestAdapter" version="3.16.1" targetFramework="net462" developmentDependency="true" />
  <package id="StyleCop.Analyzers" version="1.0.0" targetFramework="net462" developmentDependency="true" />
  <package id="XrmMockup365" version="1.2.0" targetFramework="net462" />
```

**Comment by magesoe** [comment]
That is a mistake I thought we fixed. You need core assemblies version 9.1

**Comment by maerger** [comment]
Thanks for outstanding support - now it's working like a charm!
